### ISSUE TITLE
Referrer Bot: bluerobot.info und weitere

### ISSUE THREAD

**Issue by BugBuster1701** [BugBuster1701/botdetection#120]
http://bluerobot.info/nw2/tregoreredonuno

**Comment by BugBuster1701** [comment]
http://specialdessous.com/
    pizza-tycoon.de
    hvd-store.com
    ads-cpm.com

jeweils von mehreren IP Adressen, sind meist geparkte Domains die zum Verkauf stehen.
Automatisch Referrer Spam Domains erkennen wenn von mehreren IPs innerhalb eines Zeitraumes?

**Comment by BugBuster1701** [comment]
success-seo.com
100dollars-seo.com
videos-for-your-business.com

**Comment by Kahmoon** [comment]
Hier mal meine Liste für Ghostrefereal Spam

qualitymarketzone.com
plaghunter.com
www.event-tracking.com
fx-ray.com
success-seo.com
www.Get-Free-Traffic-Now.com
e-buyeasy.com
buttons-for-website.com
videos-for-your-business.com
chinese-amezon.com
creativebiz.de
fanyi.baidu.com
yourserverisdown.com
ilovevitaly.com
blackhatworth.com
hulfingtonpost.com
Resellerclub.com
DirectI.com
cenoval.ru
bestwebsitesawards.com
o-o-6-o-o.com
humanorightswatch.org
addons.mozilla.org
googlsucks.com
theguardlan.com
VitalityrulesGoogle
buy-cheap-online.info
site3.free-share-buttons.com
www.Get-Free-Traffic-Now.com
sanjosestartups.com
howtostopreferralspam.eu
100dollars-seo.com
event-tracking.com
erot.co
yourserverisdown.com
priceg.com
blackhatworth.com
free-floating-buttons.com
get-free-social-traffic.com
chinese-amezon.com
satellite.maps.ilovevitaly.com
traffic2money.com
site#.floating-share-buttons.com
e-buyeasy.com
wpsecuritycheck.co.uk
wpthemedetector.co.uk
erot.co
webmonetizer.net
howtostopreferralspam.eu
trafficmonetizer.org
wpsecuritycheck.co.uk
wpthemedetector.co.uk
trafficmonetize.org
4webmasters.org
websites-reviews.com
sanjosestartups.com
site1.floating-share-buttons.com site3.floating-share-buttons.com torture.ml
amanda-porn.ga
generalporn.org
depositfiles-porn.ga
youporn-forum.ga
site2.floating-share-buttons.com s.click.aliexpress.com/e/ay3rfmzfi
www.event-tracking.com
webmaster-traffic.com
vitaly rules google
rapidgator-porn.ga
meendo-free-traffic.ga
buy-cheap-online.info
www.Get-Free-Traffic-Now.com
addons.mozilla.org
googlsucks.com
simple-share-buttons.com
social-buttons.com
s.click.aliexpress.com
o-o-8-o-o.com
humanorightswatch.org
o-o-6-o-o.com
bestwebsitesawards.com
resellerclub scam
darodar.com
hulfingtonpost.com
ilovevitaly.com
blackhatworth.com
resellerclub scam
forum20.smailik.org
buyeasy.com

**Comment by BugBuster1701** [comment]
http://www.analyticsedge.com/2014/12/removing-referral-spam-google-analytics/

**Comment by georgi56** [comment]
Hier zusätzlich die auf meiner Seite:

video--production.com
bluerobot.info
29263731.videos-for-your-business.com
duckduckgo.com
justprofit.xyz
semaltmedia.com
yandex.ru

PS.: Bin mir nicht sicher, ob das alle Ghostrefereal sind.
