### ISSUE TITLE
Fehler in 4.1.0-RC1mit /vendor/autoload.php

### ISSUE THREAD

**Issue by johannes-bittner** [BugBuster1701/botdetection#136]
Ich erhalte nach dem Aufbau des internen Caches mit Version 4.1.0-RC1, Build 7 (Contao 3.5.6) folgende Fehlermeldung im Backend: 

> Warning: require(/PFAD/system/cache/config/../vendor/autoload.php): failed to open stream: No such file or directory in system/cache/config/config.php on line 575

> #0 system/cache/config/config.php(575): __error(2, 'require(/kunden...', '/kunden/PFAD_...', 575, Array)
> #1 system/cache/config/config.php(575): require()
> #2 system/modules/core/library/Contao/Config.php(130): include('/kunden/PFAD_...')
> #3 system/modules/core/library/Contao/Config.php(108): Contao\Config->initialize()
> #4 system/initialize.php(162): Contao\Config::getInstance()
> #5 contao/main.php(16): require('/PFAD_...')
> #6 {main}

> Fatal error: require(): Failed opening required '/PFAD/system/cache/config/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /PFAD/system/cache/config/config.php on line 575

Das Löschen des Caches und die Deaktivierung in den Einstellungen löst das temporär, tritt aber reproduzierbar wieder auf. Contao-Check ist grün.

**Comment by BugBuster1701** [comment]
Lösche per Hand den Cache (das Verzeichnis system/cache/config reicht),
lösche die Datei system/modules/botdetection/config/config.php, 
installiere das Build 8.
Damit sollte es dann gehen.

**Comment by BugBuster1701** [comment]
Wenn Cache deaktiviert und gelöscht ist, kannste natürlich gleich die Build 8 installieren/updaten.

**Comment by johannes-bittner** [comment]
Super, funkt.
